/**
 * Copyright whaa whaa
 * Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.
 */

import { Viewer } from "@snowtop/ent";
import {
  ContactInfoBaseMixin,
  IContactInfoBase,
} from "../generated/mixins/contact_info_base";

export interface IContactInfo<TViewer extends Viewer = Viewer>
  extends IContactInfoBase<TViewer> {
  isContactInfo(): boolean;

  // add custom fields
}

type Constructor<T extends IContactInfo = IContactInfo> = new (
  ...args: any[]
) => T;

export function isContactInfo(ent: unknown): ent is IContactInfo {
  const o = ent as IContactInfo;
  return (o.isContactInfo && o.isContactInfo()) ?? false;
}

export function ContactInfoMixin<T extends Constructor>(BaseClass: T) {
  return class ContactInfoMixin
    extends ContactInfoBaseMixin(BaseClass)
    implements IContactInfo
  {
    isContactInfo() {
      return true;
    }

    // add custom fields implementation
  };
}
