/**
 * Copyright whaa whaa
 * Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.
 */

import {
  FeedbackBaseMixin,
  IFeedbackBase,
  isFeedback,
} from "../generated/mixins/feedback_base";

export { isFeedback };

type Constructor<T = {}> = new (...args: any[]) => T;

export interface IFeedback extends IFeedbackBase {
  // add custom fields
}

export function FeedbackMixin<T extends Constructor>(BaseClass: T) {
  // THIS DOESN'T WORK BECAUSE DOESN'T HAVE IFeedbackBase methods
  return class FeedbackMixin
    extends FeedbackBaseMixin(BaseClass)
    implements IFeedback {
    // add custom fields implementation
  };
}
