// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"context"
	"sync"
	"time"

	"github.com/lolopinto/ent/ent"
	"github.com/lolopinto/ent/ent/cast"
	"github.com/lolopinto/ent/ent/viewer"
	"github.com/lolopinto/ent/internal/test_schema/graphql/auth"
	"github.com/lolopinto/ent/internal/test_schema/graphql/block"
	"github.com/lolopinto/ent/internal/test_schema/graphql/log"
	"github.com/lolopinto/ent/internal/test_schema/models"
	"github.com/lolopinto/ent/internal/test_schema/models/contact/action"
	action1 "github.com/lolopinto/ent/internal/test_schema/models/event/action"
	action2 "github.com/lolopinto/ent/internal/test_schema/models/user/action"
)

type Resolver struct{}

func (r *Resolver) Contact() ContactResolver {
	return &contactResolver{r}
}
func (r *Resolver) ContactEmail() ContactEmailResolver {
	return &contactEmailResolver{r}
}
func (r *Resolver) Event() EventResolver {
	return &eventResolver{r}
}
func (r *Resolver) Mutation() MutationResolver {
	return &mutationResolver{r}
}
func (r *Resolver) Query() QueryResolver {
	return &queryResolver{r}
}
func (r *Resolver) User() UserResolver {
	return &userResolver{r}
}

type contactResolver struct{ *Resolver }

func (r *contactResolver) AllowList(ctx context.Context, obj *models.Contact) ([]*models.User, error) {
	return obj.LoadAllowList()
}

func (r *contactResolver) ContactEmails(ctx context.Context, obj *models.Contact) ([]*models.ContactEmail, error) {
	return obj.LoadContactEmails()
}

type contactEmailResolver struct{ *Resolver }

func (r *contactEmailResolver) Contact(ctx context.Context, obj *models.ContactEmail) (*models.Contact, error) {
	return obj.LoadContact()
}

type eventResolver struct{ *Resolver }

func (r *eventResolver) Attending(ctx context.Context, obj *models.Event) ([]*models.User, error) {
	return obj.LoadAttending()
}

func (r *eventResolver) Creator(ctx context.Context, obj *models.Event) (*models.User, error) {
	return obj.LoadCreator()
}

func (r *eventResolver) Declined(ctx context.Context, obj *models.Event) ([]*models.User, error) {
	return obj.LoadDeclined()
}

func (r *eventResolver) Hosts(ctx context.Context, obj *models.Event) ([]*models.User, error) {
	return obj.LoadHosts()
}

func (r *eventResolver) Invited(ctx context.Context, obj *models.Event) ([]*models.User, error) {
	return obj.LoadInvited()
}

func (r *eventResolver) User(ctx context.Context, obj *models.Event) (*models.User, error) {
	return obj.LoadUser()
}

func (r *eventResolver) ViewerRsvpStatus(ctx context.Context, obj *models.Event) (*EventRsvpStatus, error) {
	enum, err := obj.ViewerRsvpStatusForGQL()
	if err != nil {
		return nil, err
	}
	// cast to enum that graphql resolve would have generated
	cast := EventRsvpStatus(*enum)
	return &cast, err
}

type mutationResolver struct{ *Resolver }

func (r *mutationResolver) AdminBlock(ctx context.Context, blockerID string, blockeeID string) (*AdminBlockResponse, error) {
	v, ctxErr := viewer.ForContext(ctx)
	if ctxErr != nil {
		return nil, ctxErr
	}
	var wg sync.WaitGroup
	wg.Add(2)
	var blockeeResult models.UserResult
	var blockerResult models.UserResult
	go models.GenLoadUser(v, blockeeID, &blockeeResult, &wg)
	go models.GenLoadUser(v, blockerID, &blockerResult, &wg)
	wg.Wait()
	if entErr := ent.CoalesceErr(&blockeeResult, &blockerResult); entErr != nil {
		return nil, entErr
	}

	err := block.AdminBlock(ctx, blockerResult.User, blockeeResult.User)
	if err != nil {
		return nil, err
	}

	return &AdminBlockResponse{
		Success: cast.ConvertToNullableBool(true),
	}, nil
}

func (r *mutationResolver) ContactCreate(ctx context.Context, input ContactCreateInput) (*ContactCreateResponse, error) {
	node, err := action.CreateContactFromContext(ctx).
		SetEmailAddress(input.EmailAddress).
		SetFirstName(input.FirstName).
		SetLastName(input.LastName).
		SetUserID(input.UserID).
		SetNilableFavorite(input.Favorite).
		SetNilableNumberOfCalls(input.NumberOfCalls).
		SetNilablePi(input.Pi).
		Save()

	if err != nil {
		return nil, err
	}

	return &ContactCreateResponse{
		Contact: node,
	}, nil
}

func (r *mutationResolver) EventCreate(ctx context.Context, input EventCreateInput) (*EventCreateResponse, error) {
	node, err := action1.CreateEventFromContext(ctx).
		SetName(input.Name).
		SetUserID(input.UserID).
		SetStartTime(input.StartTime).
		SetNilableEndTime(input.EndTime).
		SetLocation(input.Location).
		Save()

	if err != nil {
		return nil, err
	}

	return &EventCreateResponse{
		Event: node,
	}, nil
}

func (r *mutationResolver) EventRsvpStatusEdit(ctx context.Context, input EventRsvpStatusEditInput) (*EventRsvpStatusEditResponse, error) {
	existingNode, err := models.LoadEventFromContext(ctx, input.EventID)
	if err != nil {
		return nil, err
	}

	node, err := action1.EditEventRsvpStatusFromContext(ctx, existingNode).
		AddRsvpStatus(input.RsvpStatus).
		AddUserID(input.UserID).
		Save()

	if err != nil {
		return nil, err
	}

	return &EventRsvpStatusEditResponse{
		Event: node,
	}, nil
}

func (r *mutationResolver) LogEvent(ctx context.Context, event string) (*LogEventResponse, error) {
	log.Log(ctx, event)

	return &LogEventResponse{
		Success: cast.ConvertToNullableBool(true),
	}, nil
}

func (r *mutationResolver) LogEvent2(ctx context.Context, event string) (*LogEvent2Response, error) {
	err := log.Log2(ctx, event)
	if err != nil {
		return nil, err
	}

	return &LogEvent2Response{
		Success: cast.ConvertToNullableBool(true),
	}, nil
}

func (r *mutationResolver) UserAddFamilyMember(ctx context.Context, input UserAddFamilyMemberInput) (*UserAddFamilyMemberResponse, error) {
	existingNode, err := models.LoadUserFromContext(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	node, err := action2.AddFamilyMemberFromContext(ctx, existingNode).
		AddFamilyMemberID(input.FamilyMemberID).
		Save()

	if err != nil {
		return nil, err
	}

	return &UserAddFamilyMemberResponse{
		User: node,
	}, nil
}

func (r *mutationResolver) UserAddFriend(ctx context.Context, input UserAddFriendInput) (*UserAddFriendResponse, error) {
	existingNode, err := models.LoadUserFromContext(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	node, err := action2.AddFriendFromContext(ctx, existingNode).
		AddFriendID(input.FriendID).
		Save()

	if err != nil {
		return nil, err
	}

	return &UserAddFriendResponse{
		User: node,
	}, nil
}

func (r *mutationResolver) UserCreate(ctx context.Context, input UserCreateInput) (*UserCreateResponse, error) {
	node, err := action2.CreateUserFromContext(ctx).
		SetEmailAddress(input.EmailAddress).
		SetFirstName(input.FirstName).
		SetLastName(input.LastName).
		SetNilableBio(input.Bio).
		Save()

	if err != nil {
		return nil, err
	}

	return &UserCreateResponse{
		User: node,
	}, nil
}

func (r *mutationResolver) UserDelete(ctx context.Context, input UserDeleteInput) (*UserDeleteResponse, error) {
	existingNode, err := models.LoadUserFromContext(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	err = action2.DeleteUserFromContext(ctx, existingNode).
		Save()

	if err != nil {
		return nil, err
	}

	return &UserDeleteResponse{
		DeletedUserID: &existingNode.ID,
	}, nil
}

func (r *mutationResolver) UserEdit(ctx context.Context, input UserEditInput) (*UserEditResponse, error) {
	existingNode, err := models.LoadUserFromContext(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	node, err := action2.EditUserFromContext(ctx, existingNode).
		SetEmailAddress(input.EmailAddress).
		SetFirstName(input.FirstName).
		SetLastName(input.LastName).
		SetNilableBio(input.Bio).
		Save()

	if err != nil {
		return nil, err
	}

	return &UserEditResponse{
		User: node,
	}, nil
}

func (r *mutationResolver) UserRemoveFamilyMember(ctx context.Context, input UserRemoveFamilyMemberInput) (*UserRemoveFamilyMemberResponse, error) {
	existingNode, err := models.LoadUserFromContext(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	node, err := action2.RemoveFamilyMemberFromContext(ctx, existingNode).
		RemoveFamilyMemberID(input.FamilyMemberID).
		Save()

	if err != nil {
		return nil, err
	}

	return &UserRemoveFamilyMemberResponse{
		User: node,
	}, nil
}

func (r *mutationResolver) UserRemoveFriend(ctx context.Context, input UserRemoveFriendInput) (*UserRemoveFriendResponse, error) {
	existingNode, err := models.LoadUserFromContext(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	node, err := action2.RemoveFriendFromContext(ctx, existingNode).
		RemoveFriendID(input.FriendID).
		Save()

	if err != nil {
		return nil, err
	}

	return &UserRemoveFriendResponse{
		User: node,
	}, nil
}

func (r *mutationResolver) ViewerBlock(ctx context.Context, userID string) (*ViewerBlockResponse, error) {
	user, userErr := models.LoadUserFromContext(ctx, userID)
	if userErr != nil {
		return nil, userErr
	}

	err := block.Block(ctx, user)
	if err != nil {
		return nil, err
	}

	return &ViewerBlockResponse{
		Success: cast.ConvertToNullableBool(true),
	}, nil
}

func (r *mutationResolver) ViewerBlockMultiple(ctx context.Context, userIDs []string) (*ViewerBlockMultipleResponse, error) {
	// TODO need an API for loading multi-ids
	v, ctxErr := viewer.ForContext(ctx)
	if ctxErr != nil {
		return nil, ctxErr
	}
	var wg sync.WaitGroup
	results := make([]*models.UserResult, len(userIDs))
	wg.Add(len(userIDs))
	for idx, id := range userIDs {
		go models.GenLoadUser(v, id, results[idx], &wg)
	}
	wg.Wait()

	var errs []error
	var users []*models.User
	for _, res := range results {
		if res.Err != nil {
			errs = append(errs, res.Err)
		} else {
			users = append(users, res.User)
		}
	}
	if err := ent.CoalesceErr(errs...); err != nil {
		return nil, err
	}

	err := block.BlockMultiple(ctx, users)
	if err != nil {
		return nil, err
	}

	return &ViewerBlockMultipleResponse{
		Success: cast.ConvertToNullableBool(true),
	}, nil
}

type queryResolver struct{ *Resolver }

func (r *queryResolver) AuthUser(ctx context.Context, email string, password string) (*AuthUserResult, error) {
	user, token, err := auth.Authenticate(ctx, email, password)
	if err != nil {
		return nil, err
	}

	return &AuthUserResult{
		User:  user,
		Token: token,
	}, nil
}

func (r *queryResolver) Contact(ctx context.Context, id string) (*models.Contact, error) {
	return models.LoadContactFromContext(ctx, id)
}

func (r *queryResolver) ContactEmail(ctx context.Context, id string) (*models.ContactEmail, error) {
	return models.LoadContactEmailFromContext(ctx, id)
}

func (r *queryResolver) Event(ctx context.Context, id string) (*models.Event, error) {
	return models.LoadEventFromContext(ctx, id)
}

func (r *queryResolver) ServerTime(ctx context.Context) (*time.Time, error) {
	ret := serverTime()
	return &ret, nil
}

func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	return models.LoadUserFromContext(ctx, id)
}

type userResolver struct{ *Resolver }

func (r *userResolver) Contacts(ctx context.Context, obj *models.User) ([]*models.Contact, error) {
	return obj.LoadContacts()
}

func (r *userResolver) DeclinedEvents(ctx context.Context, obj *models.User) ([]*models.Event, error) {
	return obj.LoadDeclinedEvents()
}

func (r *userResolver) Events(ctx context.Context, obj *models.User) ([]*models.Event, error) {
	return obj.LoadEvents()
}

func (r *userResolver) EventsAttending(ctx context.Context, obj *models.User) ([]*models.Event, error) {
	return obj.LoadEventsAttending()
}

func (r *userResolver) FamilyMembers(ctx context.Context, obj *models.User) ([]*models.User, error) {
	return obj.LoadFamilyMembers()
}

func (r *userResolver) Friends(ctx context.Context, obj *models.User) ([]*models.User, error) {
	return obj.LoadFriends()
}

func (r *userResolver) InvitedEvents(ctx context.Context, obj *models.User) ([]*models.Event, error) {
	return obj.LoadInvitedEvents()
}
