package graphql

import "github.com/lolopinto/ent/ent/auth"

func init() {
	// needed to login the user
	// this has logspew when we have both because they both try and authenticate the user
	// and the keys aren't the same
	// This is rare and the worst thing here is logspew so fine for now
	// probably worth at some point having the audience or issue or something in the jwt
	// let us know we should only check for the jwt generated by said handler
	auth.Register("phone_auth", phoneAuthHandler)
	auth.Register("email_auth", emailAuthHandler)
}
