version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-local
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports: 
      - 4000:4000
      - 9229:9229 # for debugger apparently
    volumes: 
      - .:/app:rw,delegated
    environment:
      # golang which we use needs the sslmode=disable bit
      - DB_CONNECTION_STRING=postgres://ola:@host.docker.internal/tsent_test?sslmode=disable
      - GITHUB_TOKEN=${GITHUB_TOKEN}


  # db_postgres:
  #   image: postgres:11-alpine
  #   ports: 
  #     - 5432:5432
  #   #user: ola
