version: '3.8'

services:
  app:
    build: 
      context: .
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    ports: 
      - 4000:4000
      - 9229:9229 # for debugger apparently
    volumes: 
      - ./:/src
    environment:
      - DB_CONNECTION_STRING=postgres://ola:@host.docker.internal/tsent_test
      - NPM_TOKEN=${NPM_TOKEN}


  # db_postgres:
  #   image: postgres:11-alpine
  #   ports: 
  #     - 5432:5432
  #   #user: ola
