# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add event_creator_edges table
add event_hosts_edges table
add edges EventToCreatorEdge, EventToHostsEdge

Revision ID: 4044b4003faa
Revises: 40655093d106
Create Date: 2019-10-23 22:09:20.170992+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4044b4003faa'
down_revision = '40655093d106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_creator_edges',
    sa.Column('id1', postgresql.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', postgresql.UUID(), nullable=False),
    sa.Column('id2', postgresql.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='event_creator_edges_id1_edge_type_id2_pkey')
    )
    op.create_table('event_hosts_edges',
    sa.Column('id1', postgresql.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', postgresql.UUID(), nullable=False),
    sa.Column('id2', postgresql.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='event_hosts_edges_id1_edge_type_id2_pkey')
    )
    op.add_edges(
      [
        {'edge_name': 'EventToCreatorEdge', 'edge_type': 'eb45df04-a2ce-4d20-9325-ef6ddb7c5c31', 'edge_table': 'event_creator_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'EventToHostsEdge', 'edge_type': '06a23665-6e2c-413a-bbb0-f53222c313dd', 'edge_table': 'event_hosts_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
      ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges(
      [
        {'edge_name': 'EventToCreatorEdge', 'edge_type': 'eb45df04-a2ce-4d20-9325-ef6ddb7c5c31', 'edge_table': 'event_creator_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'EventToHostsEdge', 'edge_type': '06a23665-6e2c-413a-bbb0-f53222c313dd', 'edge_table': 'event_hosts_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
      ]
    )
    op.drop_table('event_hosts_edges')
    op.drop_table('event_creator_edges')
    # ### end Alembic commands ###
