# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add db extension vector
add assoc_edge_config table
add note_chunks table
add index note_chunks_note_id_idx to note_chunks
add index note_chunks_unique_ordinal to note_chunks
add index note_chunks_workspace_id_idx to note_chunks
add note_chunks_edges table
add index note_chunks_edges_time_idx to note_chunks_edges
add note_saved_by_edges table
add index note_saved_by_edges_time_idx to note_saved_by_edges
add note_tags_edges table
add index note_tags_edges_time_idx to note_tags_edges
add notes table
add index notes_author_id_idx to notes
add index notes_workspace_id_idx to notes
add index workspace_notes_status_idx to notes
add tags table
add index tags_workspace_id_idx to tags
add index workspace_tags_unique_name to tags
add user_created_workspaces_edges table
add index user_created_workspaces_edges_time_idx to user_created_workspaces_edges
add user_notes_authored_edges table
add index user_notes_authored_edges_time_idx to user_notes_authored_edges
add users table
add workspace_members_edges table
add index workspace_members_edges_time_idx to workspace_members_edges
add workspace_note_chunks_edges table
add index workspace_note_chunks_edges_time_idx to workspace_note_chunks_edges
add workspace_notes_edges table
add index workspace_notes_edges_time_idx to workspace_notes_edges
add workspace_tags_edges table
add index workspace_tags_edges_time_idx to workspace_tags_edges
add workspaces table
add index workspaces_creator_id_idx to workspaces
add edges NoteToChunksEdge, NoteToSavedByEdge, NoteToTagsEdge, TagToNotesEdge, UserToCreatedWorkspacesEdge, UserToNotesAuthoredEdge, UserToSavedNotesEdge, UserToWorkspacesEdge, WorkspaceToMembersEdge, WorkspaceToNoteChunksEdge, WorkspaceToNotesEdge, WorkspaceToTagsEdge

Revision ID: 36db2ecb4a56
Revises: 
Create Date: 2026-03-29 22:45:57.491241+00:00

"""
from alembic import op #noqa
import sqlalchemy as sa
import auto_schema


# revision identifiers, used by Alembic.
revision = '36db2ecb4a56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_db_extension({'name': 'vector', 'managed': True, 'version': None, 'install_schema': None, 'runtime_schemas': ['public'], 'drop_cascade': False})
    op.create_table('assoc_edge_config',
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('edge_name', sa.Text(), nullable=False),
    sa.Column('symmetric_edge', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('inverse_edge_type', sa.UUID(), nullable=True),
    sa.Column('edge_table', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['inverse_edge_type'], ['assoc_edge_config.edge_type'], name='assoc_edge_config_inverse_edge_type_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('edge_type', name='assoc_edge_config_edge_type_pkey'),
    sa.UniqueConstraint('edge_name', name='assoc_edge_config_unique_edge_name')
    )
    op.create_table('note_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', auto_schema.schema_item.CustomSQLAlchemyType('vector(6)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='note_chunks_id_pkey')
    )
    op.create_index('note_chunks_note_id_idx', 'note_chunks', ['note_id'], unique=False)
    op.create_index('note_chunks_unique_ordinal', 'note_chunks', ['note_id', 'ordinal'], unique=True)
    op.create_index('note_chunks_workspace_id_idx', 'note_chunks', ['workspace_id'], unique=False)
    op.create_table('note_chunks_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='note_chunks_edges_pkey')
    )
    op.create_index('note_chunks_edges_time_idx', 'note_chunks_edges', ['time'], unique=False)
    op.create_table('note_saved_by_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='note_saved_by_edges_pkey')
    )
    op.create_index('note_saved_by_edges_time_idx', 'note_saved_by_edges', ['time'], unique=False)
    op.create_table('note_tags_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='note_tags_edges_pkey')
    )
    op.create_index('note_tags_edges_time_idx', 'note_tags_edges', ['time'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='DRAFT', nullable=False),
    sa.PrimaryKeyConstraint('id', name='notes_id_pkey')
    )
    op.create_index('notes_author_id_idx', 'notes', ['author_id'], unique=False)
    op.create_index('notes_workspace_id_idx', 'notes', ['workspace_id'], unique=False)
    op.create_index('workspace_notes_status_idx', 'notes', ['workspace_id', 'status'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='tags_id_pkey')
    )
    op.create_index('tags_workspace_id_idx', 'tags', ['workspace_id'], unique=False)
    op.create_index('workspace_tags_unique_name', 'tags', ['workspace_id', 'name'], unique=True)
    op.create_table('user_created_workspaces_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='user_created_workspaces_edges_pkey')
    )
    op.create_index('user_created_workspaces_edges_time_idx', 'user_created_workspaces_edges', ['time'], unique=False)
    op.create_table('user_notes_authored_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='user_notes_authored_edges_pkey')
    )
    op.create_index('user_notes_authored_edges_time_idx', 'user_notes_authored_edges', ['time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email_address', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_id_pkey'),
    sa.UniqueConstraint('email_address', name='users_unique_email_address')
    )
    op.create_table('workspace_members_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='workspace_members_edges_pkey')
    )
    op.create_index('workspace_members_edges_time_idx', 'workspace_members_edges', ['time'], unique=False)
    op.create_table('workspace_note_chunks_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='workspace_note_chunks_edges_pkey')
    )
    op.create_index('workspace_note_chunks_edges_time_idx', 'workspace_note_chunks_edges', ['time'], unique=False)
    op.create_table('workspace_notes_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='workspace_notes_edges_pkey')
    )
    op.create_index('workspace_notes_edges_time_idx', 'workspace_notes_edges', ['time'], unique=False)
    op.create_table('workspace_tags_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='workspace_tags_edges_pkey')
    )
    op.create_index('workspace_tags_edges_time_idx', 'workspace_tags_edges', ['time'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.Text(), server_default='text-embedding-3-small', nullable=False),
    sa.PrimaryKeyConstraint('id', name='workspaces_id_pkey'),
    sa.UniqueConstraint('slug', name='workspaces_unique_slug')
    )
    op.create_index('workspaces_creator_id_idx', 'workspaces', ['creator_id'], unique=False)
    op.add_edges([
    {'edge_name': 'NoteToChunksEdge', 'edge_type': 'eb12d548-7ce4-45d5-bab0-a30daaeae141', 'edge_table': 'note_chunks_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'NoteToSavedByEdge', 'edge_type': '18fe105e-31b2-47fa-846a-61f8f8014697', 'edge_table': 'note_saved_by_edges', 'symmetric_edge': False, 'inverse_edge_type': 'b6dfcb48-24c4-47b6-8cf8-0e2bc1044d61'},
    {'edge_name': 'NoteToTagsEdge', 'edge_type': '1e6c4bae-ec0d-483e-9622-6a2f5d86344a', 'edge_table': 'note_tags_edges', 'symmetric_edge': False, 'inverse_edge_type': '23466598-29d2-4610-9f35-b785afb25f93'},
    {'edge_name': 'TagToNotesEdge', 'edge_type': '23466598-29d2-4610-9f35-b785afb25f93', 'edge_table': 'note_tags_edges', 'symmetric_edge': False, 'inverse_edge_type': '1e6c4bae-ec0d-483e-9622-6a2f5d86344a'},
    {'edge_name': 'UserToCreatedWorkspacesEdge', 'edge_type': '59d27b35-fb81-4ed2-b2db-165bbc08bb64', 'edge_table': 'user_created_workspaces_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'UserToNotesAuthoredEdge', 'edge_type': 'd8a450e8-6827-44a5-a3f1-ec608d42eb3e', 'edge_table': 'user_notes_authored_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'UserToSavedNotesEdge', 'edge_type': 'b6dfcb48-24c4-47b6-8cf8-0e2bc1044d61', 'edge_table': 'note_saved_by_edges', 'symmetric_edge': False, 'inverse_edge_type': '18fe105e-31b2-47fa-846a-61f8f8014697'},
    {'edge_name': 'UserToWorkspacesEdge', 'edge_type': '91c248cf-d0fd-4dec-a631-358f96fcacc7', 'edge_table': 'workspace_members_edges', 'symmetric_edge': False, 'inverse_edge_type': '95c5bb94-6c48-4503-93ef-5d66df08a7fe'},
    {'edge_name': 'WorkspaceToMembersEdge', 'edge_type': '95c5bb94-6c48-4503-93ef-5d66df08a7fe', 'edge_table': 'workspace_members_edges', 'symmetric_edge': False, 'inverse_edge_type': '91c248cf-d0fd-4dec-a631-358f96fcacc7'},
    {'edge_name': 'WorkspaceToNoteChunksEdge', 'edge_type': '4663a6e9-8193-47bc-ad9e-14933d2e6295', 'edge_table': 'workspace_note_chunks_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'WorkspaceToNotesEdge', 'edge_type': '707b0be4-6855-419d-af29-12551c3adf63', 'edge_table': 'workspace_notes_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'WorkspaceToTagsEdge', 'edge_type': 'efb4678b-f768-4ba1-b9a1-913c9beb2ec5', 'edge_table': 'workspace_tags_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
    {'edge_name': 'NoteToChunksEdge', 'edge_type': 'eb12d548-7ce4-45d5-bab0-a30daaeae141', 'edge_table': 'note_chunks_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'NoteToSavedByEdge', 'edge_type': '18fe105e-31b2-47fa-846a-61f8f8014697', 'edge_table': 'note_saved_by_edges', 'symmetric_edge': False, 'inverse_edge_type': 'b6dfcb48-24c4-47b6-8cf8-0e2bc1044d61'},
    {'edge_name': 'NoteToTagsEdge', 'edge_type': '1e6c4bae-ec0d-483e-9622-6a2f5d86344a', 'edge_table': 'note_tags_edges', 'symmetric_edge': False, 'inverse_edge_type': '23466598-29d2-4610-9f35-b785afb25f93'},
    {'edge_name': 'TagToNotesEdge', 'edge_type': '23466598-29d2-4610-9f35-b785afb25f93', 'edge_table': 'note_tags_edges', 'symmetric_edge': False, 'inverse_edge_type': '1e6c4bae-ec0d-483e-9622-6a2f5d86344a'},
    {'edge_name': 'UserToCreatedWorkspacesEdge', 'edge_type': '59d27b35-fb81-4ed2-b2db-165bbc08bb64', 'edge_table': 'user_created_workspaces_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'UserToNotesAuthoredEdge', 'edge_type': 'd8a450e8-6827-44a5-a3f1-ec608d42eb3e', 'edge_table': 'user_notes_authored_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'UserToSavedNotesEdge', 'edge_type': 'b6dfcb48-24c4-47b6-8cf8-0e2bc1044d61', 'edge_table': 'note_saved_by_edges', 'symmetric_edge': False, 'inverse_edge_type': '18fe105e-31b2-47fa-846a-61f8f8014697'},
    {'edge_name': 'UserToWorkspacesEdge', 'edge_type': '91c248cf-d0fd-4dec-a631-358f96fcacc7', 'edge_table': 'workspace_members_edges', 'symmetric_edge': False, 'inverse_edge_type': '95c5bb94-6c48-4503-93ef-5d66df08a7fe'},
    {'edge_name': 'WorkspaceToMembersEdge', 'edge_type': '95c5bb94-6c48-4503-93ef-5d66df08a7fe', 'edge_table': 'workspace_members_edges', 'symmetric_edge': False, 'inverse_edge_type': '91c248cf-d0fd-4dec-a631-358f96fcacc7'},
    {'edge_name': 'WorkspaceToNoteChunksEdge', 'edge_type': '4663a6e9-8193-47bc-ad9e-14933d2e6295', 'edge_table': 'workspace_note_chunks_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'WorkspaceToNotesEdge', 'edge_type': '707b0be4-6855-419d-af29-12551c3adf63', 'edge_table': 'workspace_notes_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'WorkspaceToTagsEdge', 'edge_type': 'efb4678b-f768-4ba1-b9a1-913c9beb2ec5', 'edge_table': 'workspace_tags_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    op.drop_index('workspaces_creator_id_idx', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('workspace_tags_edges_time_idx', table_name='workspace_tags_edges')
    op.drop_table('workspace_tags_edges')
    op.drop_index('workspace_notes_edges_time_idx', table_name='workspace_notes_edges')
    op.drop_table('workspace_notes_edges')
    op.drop_index('workspace_note_chunks_edges_time_idx', table_name='workspace_note_chunks_edges')
    op.drop_table('workspace_note_chunks_edges')
    op.drop_index('workspace_members_edges_time_idx', table_name='workspace_members_edges')
    op.drop_table('workspace_members_edges')
    op.drop_table('users')
    op.drop_index('user_notes_authored_edges_time_idx', table_name='user_notes_authored_edges')
    op.drop_table('user_notes_authored_edges')
    op.drop_index('user_created_workspaces_edges_time_idx', table_name='user_created_workspaces_edges')
    op.drop_table('user_created_workspaces_edges')
    op.drop_index('workspace_tags_unique_name', table_name='tags')
    op.drop_index('tags_workspace_id_idx', table_name='tags')
    op.drop_table('tags')
    op.drop_index('workspace_notes_status_idx', table_name='notes')
    op.drop_index('notes_workspace_id_idx', table_name='notes')
    op.drop_index('notes_author_id_idx', table_name='notes')
    op.drop_table('notes')
    op.drop_index('note_tags_edges_time_idx', table_name='note_tags_edges')
    op.drop_table('note_tags_edges')
    op.drop_index('note_saved_by_edges_time_idx', table_name='note_saved_by_edges')
    op.drop_table('note_saved_by_edges')
    op.drop_index('note_chunks_edges_time_idx', table_name='note_chunks_edges')
    op.drop_table('note_chunks_edges')
    op.drop_index('note_chunks_workspace_id_idx', table_name='note_chunks')
    op.drop_index('note_chunks_unique_ordinal', table_name='note_chunks')
    op.drop_index('note_chunks_note_id_idx', table_name='note_chunks')
    op.drop_table('note_chunks')
    op.drop_table('assoc_edge_config')
    op.drop_db_extension({'name': 'vector', 'managed': True, 'version': None, 'install_schema': None, 'runtime_schemas': ['public'], 'drop_cascade': False})
    # ### end Alembic commands ###
