// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { GraphQLSchema } from "graphql";
import {
  AccountCreateInputType,
  AccountCreatePayloadType,
} from "src/graphql/mutations/generated/account/account_create_type";
import {
  AccountDeleteInputType,
  AccountDeletePayloadType,
} from "src/graphql/mutations/generated/account/account_delete_type";
import {
  AccountEditInputType,
  AccountEditPayloadType,
} from "src/graphql/mutations/generated/account/account_edit_type";
import { MutationType } from "src/graphql/mutations/generated/mutation_type";
import {
  TodoChangeStatusInputType,
  TodoChangeStatusPayloadType,
} from "src/graphql/mutations/generated/todo/todo_change_status_type";
import {
  TodoCreateInputType,
  TodoCreatePayloadType,
} from "src/graphql/mutations/generated/todo/todo_create_type";
import {
  TodoDeleteInputType,
  TodoDeletePayloadType,
} from "src/graphql/mutations/generated/todo/todo_delete_type";
import {
  TodoRenameInputType,
  TodoRenamePayloadType,
} from "src/graphql/mutations/generated/todo/todo_rename_type";
import { QueryType } from "src/graphql/resolvers/generated/query_type";
import {
  AccountToTagsConnectionType,
  AccountToTodosConnectionType,
  AccountType,
  TagType,
  TodoType,
} from "./resolvers";

export default new GraphQLSchema({
  query: QueryType,
  mutation: MutationType,
  types: [
    AccountType,
    TagType,
    TodoType,
    AccountToTagsConnectionType(),
    AccountToTodosConnectionType(),
    AccountCreateInputType,
    AccountCreatePayloadType,
    AccountDeleteInputType,
    AccountDeletePayloadType,
    AccountEditInputType,
    AccountEditPayloadType,
    TodoChangeStatusInputType,
    TodoChangeStatusPayloadType,
    TodoCreateInputType,
    TodoCreatePayloadType,
    TodoDeleteInputType,
    TodoDeletePayloadType,
    TodoRenameInputType,
    TodoRenamePayloadType,
  ],
});
