// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { UserToInvitedEventsQueryBase } from "src/ent/internal";
export class UserToInvitedEventsQuery extends UserToInvitedEventsQueryBase {}
