// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { UserToDeclinedEventsQueryBase } from "src/ent/internal";
export class UserToDeclinedEventsQuery extends UserToDeclinedEventsQueryBase {}
