// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { UserToEventsAttendingQueryBase } from "src/ent/internal";
export class UserToEventsAttendingQuery extends UserToEventsAttendingQueryBase {}
