# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column name to table guests
add column title to table guests
modify nullable value of column email_address from False to True
drop column last_name
drop column first_name

Revision ID: 0bde8f30cee9
Revises: dbedcbbdbbc1
Create Date: 2021-03-19 21:02:18.558415+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0bde8f30cee9'
down_revision = 'dbedcbbdbbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('guests', sa.Column('title', sa.Text(), nullable=True))
    op.alter_column('guests', 'email_address',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.drop_column('guests', 'last_name')
    op.drop_column('guests', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('first_name', sa.TEXT(),
                                      autoincrement=False, nullable=False))
    op.add_column('guests', sa.Column('last_name', sa.TEXT(),
                                      autoincrement=False, nullable=False))
    op.alter_column('guests', 'email_address',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.drop_column('guests', 'title')
    op.drop_column('guests', 'name')
    # ### end Alembic commands ###
