# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add auth_codes table

Revision ID: 19e7969c6a61
Revises: 2a5627d47472
Create Date: 2021-01-29 23:20:23.550366+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19e7969c6a61'
down_revision = '2a5627d47472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_codes',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('code', sa.Text(), nullable=False),
                    sa.Column('guest_id', postgresql.UUID(), nullable=False),
                    sa.Column('email_address', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['guest_id'], [
                        'guests.id'], name='auth_codes_guest_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='auth_codes_id_pkey'),
                    sa.UniqueConstraint(
                        'email_address', 'code', name='uniqueCode'),
                    sa.UniqueConstraint(
                        'guest_id', name='auth_codes_unique_guest_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_codes')
    # ### end Alembic commands ###
