# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column guest_data_id to table guests

Revision ID: 208fec772f6d
Revises: 873eb4e5e83e
Create Date: 2023-08-04 21:52:41.911958+00:00

"""
from alembic import op
import sqlalchemy as sa
import auto_schema
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '208fec772f6d'
down_revision = '873eb4e5e83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column(
        'guest_data_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'guest_data_id')
    # ### end Alembic commands ###
