# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add index event_activities_event_id_idx to event_activities
add index events_creator_id_idx to events
add index guest_data_event_id_idx to guest_data
add index guest_data_guest_id_idx to guest_data
add index guest_groups_event_id_idx to guest_groups
add index guests_event_id_idx to guests
add index guests_guest_group_id_idx to guests

Revision ID: 3bef7bbb4460
Revises: cb5cd2b9aa5f
Create Date: 2021-05-03 18:37:02.432088+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3bef7bbb4460'
down_revision = 'cb5cd2b9aa5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('event_activities_event_id_idx',
                    'event_activities', ['event_id'], unique=False)
    op.create_index('events_creator_id_idx', 'events',
                    ['creator_id'], unique=False)
    op.create_index('guest_data_event_id_idx', 'guest_data',
                    ['event_id'], unique=False)
    op.create_index('guest_data_guest_id_idx', 'guest_data',
                    ['guest_id'], unique=False)
    op.create_index('guest_groups_event_id_idx',
                    'guest_groups', ['event_id'], unique=False)
    op.create_index('guests_event_id_idx', 'guests',
                    ['event_id'], unique=False)
    op.create_index('guests_guest_group_id_idx', 'guests',
                    ['guest_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('guests_guest_group_id_idx', table_name='guests')
    op.drop_index('guests_event_id_idx', table_name='guests')
    op.drop_index('guest_groups_event_id_idx', table_name='guest_groups')
    op.drop_index('guest_data_guest_id_idx', table_name='guest_data')
    op.drop_index('guest_data_event_id_idx', table_name='guest_data')
    op.drop_index('events_creator_id_idx', table_name='events')
    op.drop_index('event_activities_event_id_idx',
                  table_name='event_activities')
    # ### end Alembic commands ###
