# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column description to table event_activities

Revision ID: 40753f0af94b
Revises: 5f5b00396248
Create Date: 2021-02-24 20:24:39.321183+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '40753f0af94b'
down_revision = '5f5b00396248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_activities', sa.Column(
        'description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_activities', 'description')
    # ### end Alembic commands ###
