# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column password to table users

Revision ID: 5f5b00396248
Revises: f9ba209220ec
Create Date: 2021-02-17 18:27:16.828886+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5f5b00396248'
down_revision = 'f9ba209220ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
