# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add index event_rsvps_time_idx to event_rsvps
add edge EventActivityToRsvpEdge

Revision ID: a15a61208c70
Revises: 3bef7bbb4460
Create Date: 2021-05-18 00:51:14.834652+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a15a61208c70'
down_revision = '3bef7bbb4460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('event_rsvps_time_idx',
                    'event_rsvps', ['time'], unique=False)
    op.add_edges([
        {'edge_name': 'EventActivityToRsvpEdge', 'edge_type': '3696b55b-d54d-41ee-a586-3ec6dc563ccb',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'EventActivityToRsvpEdge', 'edge_type': '3696b55b-d54d-41ee-a586-3ec6dc563ccb',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    op.drop_index('event_rsvps_time_idx', table_name='event_rsvps')
    # ### end Alembic commands ###
