# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column tag to table guest_groups
add column tag to table guests

Revision ID: dc4fb142beaf
Revises: 208fec772f6d
Create Date: 2023-08-16 17:28:06.246995+00:00

"""
from alembic import op
import sqlalchemy as sa
import auto_schema
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'dc4fb142beaf'
down_revision = '208fec772f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_groups', sa.Column('tag', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'tag')
    op.drop_column('guest_groups', 'tag')
    # ### end Alembic commands ###
