# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add assoc_edge_config table
add event_rsvps table
add edges EventActivityToAttendingEdge, EventActivityToDeclinedEdge, EventActivityToInvitesEdge, GuestGroupToInvitedEventsEdge, GuestToAttendingEventsEdge, GuestToDeclinedEventsEdge

Revision ID: fd8bc05fbc78
Revises: c51c521d5401
Create Date: 2021-01-15 20:09:34.647395+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd8bc05fbc78'
down_revision = 'c51c521d5401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assoc_edge_config',
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('edge_name', sa.Text(), nullable=False),
                    sa.Column('symmetric_edge', sa.Boolean(),
                              server_default='false', nullable=False),
                    sa.Column('inverse_edge_type',
                              postgresql.UUID(), nullable=True),
                    sa.Column('edge_table', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['inverse_edge_type'], ['assoc_edge_config.edge_type'],
                                            name='assoc_edge_config_inverse_edge_type_fkey', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint(
                        'edge_type', name='assoc_edge_config_edge_type_pkey'),
                    sa.UniqueConstraint(
                        'edge_name', name='assoc_edge_config_unique_edge_name')
                    )
    op.create_table('event_rsvps',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2',
                                            name='event_rsvps_id1_edge_type_id2_pkey')
                    )
    op.add_edges([
        {'edge_name': 'EventActivityToAttendingEdge', 'edge_type': '8025c416-c0a9-42dd-9bf4-f97f283d31a2',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': 'ea0de57e-25de-47ab-8ddc-324f41c892a3'},
        {'edge_name': 'EventActivityToDeclinedEdge', 'edge_type': 'f3ff6b74-c055-4562-b5dd-07e4e2d8c8e3',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': '5798e422-75d3-42ac-9ef8-30bd35e34f9f'},
        {'edge_name': 'EventActivityToInvitesEdge', 'edge_type': '64ef93f6-7edf-42ce-a3e4-8c30d9851645',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': '759e4abe-f866-41b7-aae8-40be4e8ab21e'},
        {'edge_name': 'GuestGroupToInvitedEventsEdge', 'edge_type': '759e4abe-f866-41b7-aae8-40be4e8ab21e',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': '64ef93f6-7edf-42ce-a3e4-8c30d9851645'},
        {'edge_name': 'GuestToAttendingEventsEdge', 'edge_type': 'ea0de57e-25de-47ab-8ddc-324f41c892a3',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': '8025c416-c0a9-42dd-9bf4-f97f283d31a2'},
        {'edge_name': 'GuestToDeclinedEventsEdge', 'edge_type': '5798e422-75d3-42ac-9ef8-30bd35e34f9f',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': 'f3ff6b74-c055-4562-b5dd-07e4e2d8c8e3'},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'EventActivityToAttendingEdge', 'edge_type': '8025c416-c0a9-42dd-9bf4-f97f283d31a2',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': 'ea0de57e-25de-47ab-8ddc-324f41c892a3'},
        {'edge_name': 'EventActivityToDeclinedEdge', 'edge_type': 'f3ff6b74-c055-4562-b5dd-07e4e2d8c8e3',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': '5798e422-75d3-42ac-9ef8-30bd35e34f9f'},
        {'edge_name': 'EventActivityToInvitesEdge', 'edge_type': '64ef93f6-7edf-42ce-a3e4-8c30d9851645',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': '759e4abe-f866-41b7-aae8-40be4e8ab21e'},
        {'edge_name': 'GuestGroupToInvitedEventsEdge', 'edge_type': '759e4abe-f866-41b7-aae8-40be4e8ab21e',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': '64ef93f6-7edf-42ce-a3e4-8c30d9851645'},
        {'edge_name': 'GuestToAttendingEventsEdge', 'edge_type': 'ea0de57e-25de-47ab-8ddc-324f41c892a3',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': '8025c416-c0a9-42dd-9bf4-f97f283d31a2'},
        {'edge_name': 'GuestToDeclinedEventsEdge', 'edge_type': '5798e422-75d3-42ac-9ef8-30bd35e34f9f',
            'edge_table': 'event_rsvps', 'symmetric_edge': False, 'inverse_edge_type': 'f3ff6b74-c055-4562-b5dd-07e4e2d8c8e3'},
    ])

    op.drop_table('event_rsvps')
    op.drop_table('assoc_edge_config')
    # ### end Alembic commands ###
