// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

export enum NodeType {
  // User is the node type for the User object. Used to identify this node in edges and other places.
  User = "user",
}

export enum EdgeType {}
