# get and install tsent
FROM golang:1.16.5-buster AS golang-image
ENV GOPATH=$HOME/go
ENV GOBIN $GOPATH/bin
ENV PATH $PATH:$GOPATH/bin
RUN go install github.com/lolopinto/ent/tsent@v0.0.19

# get and install auto_schema
FROM python:3.8.11-buster AS python-image
RUN python -m venv /opt/venv
# Make sure we use the virtualenv
ENV PATH /opt/venv/bin:$PATH

RUN python3 -m pip install auto_schema==0.0.7

# final image needs to be python-based to have auto-schema work
FROM python:3.8.11-slim AS final-image
COPY --from=golang-image /go/bin/tsent /go/bin/tsent
COPY --from=python-image /opt/venv /opt/venv

ENV PATH /opt/venv/bin:$PATH
ENV PATH /go/bin:$PATH

# this is associating this image with this repo
LABEL org.opencontainers.image.source https://github.com/lolopinto/ent

# install node and dependencies
RUN \
  apt-get update && \
  # wget and gnupg are dependencies needed below
  apt-get install -yqq wget gnupg && \
  echo "deb https://deb.nodesource.com/node_{{.NodeVersion}}.x buster main" > /etc/apt/sources.list.d/nodesource.list && \
  wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
  wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  apt-get update && \
  apt-get install -yqq nodejs yarn && \
  apt-get autoremove wget -yqq && \
  rm -rf /var/lib/apt/lists/*

{{ if .Development -}}

RUN apt update && apt --assume-yes install zsh && \
  rm -rf /var/lib/apt/lists/*

RUN npm install -g typescript prettier ts-node

WORKDIR /app
RUN npm install --save-dev tsconfig-paths 

{{ end -}}

CMD ["node"]

