ARG GOLANG_VERSION={{.TsentVersion}}
ARG AUTO_SCHEMA_VERSION={{.AutoSchemaVersion}}
ARG NODE_VERSION={{.NodeVersion}}
ARG DOCKER_TAG={{.DockerTag}}

# get and install tsent
FROM golang:1.23.3-bullseye AS golang-image
ARG GOLANG_VERSION
ARG DOCKER_TAG
ENV GOPATH=$HOME/go
ENV GOBIN $GOPATH/bin
ENV PATH $PATH:$GOPATH/bin
ARG TARGETOS TARGETARCH

# RUN --mount=target=. \
#   --mount=type=cache,target=/root/.cache/go-build \
#   --mount=type=cache,target=/go/pkg \
RUN  GOOS=$TARGETOS GOARCH=$TARGETARCH go install -ldflags="-X 'github.com/lolopinto/ent/internal/build_info.DockerVersion=$DOCKER_TAG' -X 'github.com/lolopinto/ent/internal/build_info.Time=$(date)'" github.com/lolopinto/ent/tsent@$GOLANG_VERSION

# get and install auto_schema
# psycopg2 error when buildplatform is used...
FROM python:3.11.0-bullseye AS python-image
ARG AUTO_SCHEMA_VERSION
RUN python -m venv /opt/venv
# Make sure we use the virtualenv
ENV PATH /opt/venv/bin:$PATH

RUN python3 -m pip install auto_schema==$AUTO_SCHEMA_VERSION
# RUN python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ auto_schema_test==$AUTO_SCHEMA_VERSION

# final image needs to be python-based to have auto-schema work
FROM python:3.11.0-slim AS final-image
ARG GOLANG_VERSION
ARG NODE_VERSION

ENV PATH /opt/venv/bin:$PATH
ENV PATH /go/bin:$PATH

# this is associating this image with this repo
LABEL org.opencontainers.image.source https://github.com/lolopinto/ent

# install node and dependencies
RUN apt-get update 
# wget and gnupg are dependencies needed below
# libpq-dev for libpq
# RUN apt-get install -yqq wget 
RUN apt-get install -yqq gnupg 
RUN apt-get install -yqq libpq-dev 
RUN apt-get install -yqq curl
RUN  apt-get install ripgrep -yqq
RUN  apt-get install -y ca-certificates curl gnupg
RUN  mkdir -p /etc/apt/keyrings
RUN  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_VERSION.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN  apt-get update
RUN  apt-get install nodejs -yqq yarn
# RUN  apt-get autoremove wget -yqq
RUN  rm -rf /var/lib/apt/lists/*

{{ if .Development -}}

RUN apt update && apt --assume-yes install zsh && \
  rm -rf /var/lib/apt/lists/*

RUN npm install -g typescript@5.4.5 
RUN npm install -g prettier@3.2.5 
RUN npm install -g ts-node@11.0.0-beta.1 
RUN npm install -g @swc/core@1.5.0 
RUN npm install -g @swc/cli@0.3.12 --verbose
RUN npm install -g @biomejs/biome@1.7.1

WORKDIR /app
RUN npm install --save-dev tsconfig-paths@4.2.0 @swc-node/register@1.6.8

{{ end -}}

COPY --from=golang-image /go/bin/tsent /go/bin/tsent
COPY --from=python-image /opt/venv /opt/venv
# RUN alias auto_schema=auto_schema_test
COPY --from=golang-image /go/pkg/mod/github.com/lolopinto/ent@$GOLANG_VERSION /go/pkg/mod/github.com/lolopinto/ent@$GOLANG_VERSION

CMD ["node"]

