// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { Viewer, ID, Ent } from "@lolopinto/ent";
import {
  Action,
  Builder,
  WriteOperation,
  Changeset,
  saveBuilder,
  saveBuilderX,
  Orchestrator,
} from "@lolopinto/ent/action";
import schema from "src/schema/holiday";
import { Holiday } from "src/ent/";

export interface HolidayInput {
  label?: string;
  date?: Date;
}

export interface HolidayAction extends Action<Holiday> {
  getInput(): HolidayInput;
}

function randomNum(): string {
  return Math.random().toString(10).substring(2);
}

export class HolidayBuilder implements Builder<Holiday> {
  orchestrator: Orchestrator<Holiday>;
  readonly placeholderID: ID;
  readonly ent = Holiday;
  private input: HolidayInput;

  public constructor(
    public readonly viewer: Viewer,
    public readonly operation: WriteOperation,
    action: HolidayAction,
    public readonly existingEnt?: Holiday | undefined,
  ) {
    this.placeholderID = `$ent.idPlaceholderID$ ${randomNum()}-Holiday`;
    this.input = action.getInput();

    this.orchestrator = new Orchestrator({
      viewer: viewer,
      operation: this.operation,
      tableName: "holidays",
      ent: Holiday,
      builder: this,
      action: action,
      schema: schema,
      editedFields: () => {
        return this.getEditedFields.apply(this);
      },
    });
  }

  getInput(): HolidayInput {
    return this.input;
  }

  updateInput(input: HolidayInput) {
    // override input
    this.input = {
      ...this.input,
      ...input,
    };
  }

  async build(): Promise<Changeset<Holiday>> {
    return this.orchestrator.build();
  }

  async valid(): Promise<boolean> {
    return this.orchestrator.valid();
  }

  async validX(): Promise<void> {
    return this.orchestrator.validX();
  }

  async save(): Promise<void> {
    await saveBuilder(this);
  }

  async saveX(): Promise<void> {
    await saveBuilderX(this);
  }

  async editedEnt(): Promise<Holiday | null> {
    return await this.orchestrator.editedEnt();
  }

  async editedEntX(): Promise<Holiday> {
    return await this.orchestrator.editedEntX();
  }

  private getEditedFields(): Map<string, any> {
    const fields = this.input;

    let result = new Map<string, any>();

    const addField = function (key: string, value: any) {
      if (value !== undefined) {
        result.set(key, value);
      }
    };
    addField("label", fields.label);
    addField("date", fields.date);
    return result;
  }

  isBuilder(node: ID | Ent | Builder<Ent>): node is Builder<Ent> {
    return (node as Builder<Ent>).placeholderID !== undefined;
  }
}
