version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: develop.Dockerfile
    container_name: todo-sqlite
    ports: 
      - 4000:4000
      - 9229:9229 # for debugger 
    volumes: 
      - .:/app:rw,delegated
    environment:
      - DB_CONNECTION_STRING=sqlite:///todo.db

