/*
 * ATTENTION: The "eval" devtool has been used (maybe by default in mode: "development").
 * This devtool is not neither made for production nor for readable output files.
 * It uses "eval()" calls to create a separate source file in the browser devtools.
 * If you are trying to read the output file, select a different devtool (https://webpack.js.org/configuration/devtool/)
 * or disable the default devtool with "devtool: false".
 * If you are looking for production-ready output files, see mode: "production" (https://webpack.js.org/configuration/mode/).
 */
/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	var __webpack_modules__ = ({

/***/ "./src/ent/const.ts":
/*!**************************!*\
  !*** ./src/ent/const.ts ***!
  \**************************/
/*! namespace exports */
/*! export EdgeType [provided] [no usage info] [missing usage info prevents renaming] */
/*! export NodeType [provided] [no usage info] [missing usage info prevents renaming] */
/*! other exports [not provided] [no usage info] */
/*! runtime requirements: __webpack_exports__, __webpack_require__.d, __webpack_require__.r, __webpack_require__.* */
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   \"NodeType\": () => /* binding */ NodeType,\n/* harmony export */   \"EdgeType\": () => /* binding */ EdgeType\n/* harmony export */ });\n// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.\nvar NodeType;\n(function (NodeType) {\n    // Address is the node type for the Address object. Used to identify this node in edges and other places.\n    NodeType[\"Address\"] = \"address\";\n    // Contact is the node type for the Contact object. Used to identify this node in edges and other places.\n    NodeType[\"Contact\"] = \"contact\";\n    // Event is the node type for the Event object. Used to identify this node in edges and other places.\n    NodeType[\"Event\"] = \"event\";\n    // User is the node type for the User object. Used to identify this node in edges and other places.\n    NodeType[\"User\"] = \"user\";\n})(NodeType || (NodeType = {}));\nvar EdgeType;\n(function (EdgeType) {\n    // EventToAttending is the edgeType for the event to attending edge.\n    EdgeType[\"EventToAttending\"] = \"6ebc0c47-ea29-4635-b991-95e44162174d\";\n    // EventToDeclined is the edgeType for the event to declined edge.\n    EdgeType[\"EventToDeclined\"] = \"db8d2454-f7b2-4147-aae1-e666daf3f3c3\";\n    // EventToHosts is the edgeType for the event to hosts edge.\n    EdgeType[\"EventToHosts\"] = \"ebe3e709-845c-4723-ac9c-29f983f2b8ea\";\n    // EventToInvited is the edgeType for the event to invited edge.\n    EdgeType[\"EventToInvited\"] = \"a72f5f64-3580-44fd-9bd0-d1335b803a46\";\n    // EventToMaybe is the edgeType for the event to maybe edge.\n    EdgeType[\"EventToMaybe\"] = \"b0f6311b-fdab-4c26-b6bf-b751e0997735\";\n    // UserToCreatedEvents is the edgeType for the user to createdevents edge.\n    EdgeType[\"UserToCreatedEvents\"] = \"daa3b2a3-8245-40ca-ae77-25bfb82578a7\";\n    // UserToDeclinedEvents is the edgeType for the user to declinedevents edge.\n    EdgeType[\"UserToDeclinedEvents\"] = \"1c7c173b-63ce-4002-b121-4a87f82047dd\";\n    // UserToEventsAttending is the edgeType for the user to eventsattending edge.\n    EdgeType[\"UserToEventsAttending\"] = \"2a98ba02-e342-4bb4-93f6-5d7ed02f5c48\";\n    // UserToFriends is the edgeType for the user to friends edge.\n    EdgeType[\"UserToFriends\"] = \"d1a9316d-090f-4b02-b393-fd9372e2c905\";\n    // UserToInvitedEvents is the edgeType for the user to invitedevents edge.\n    EdgeType[\"UserToInvitedEvents\"] = \"e439f2b2-d93a-4d1a-83f0-865bda5c8337\";\n    // UserToMaybeEvents is the edgeType for the user to maybeevents edge.\n    EdgeType[\"UserToMaybeEvents\"] = \"8d5b1dee-ce65-452e-9f8d-78eca1993800\";\n    // UserToSelfContact is the edgeType for the user to selfcontact edge.\n    EdgeType[\"UserToSelfContact\"] = \"d504201d-cf3f-4eef-b6a0-0b46a7ae186b\";\n})(EdgeType || (EdgeType = {}));\n\n\n//# sourceURL=webpack:///./src/ent/const.ts?");

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		if(__webpack_module_cache__[moduleId]) {
/******/ 			return __webpack_module_cache__[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => Object.prototype.hasOwnProperty.call(obj, prop)
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
/******/ 	// startup
/******/ 	// Load entry module
/******/ 	// This entry module is referenced by other modules so it can't be inlined
/******/ 	__webpack_require__("./src/ent/const.ts");
/******/ })()
;