// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { Viewer, ID, Ent } from "@lolopinto/ent";
import {
  Action,
  Builder,
  WriteOperation,
  Changeset,
  saveBuilder,
  saveBuilderX,
  Orchestrator,
} from "@lolopinto/ent/action";
import schema from "src/schema/guest_group";
import { GuestGroup, Event } from "src/ent/";

export interface GuestGroupInput {
  invitationName?: string;
  eventID?: ID | Builder<Event>;
}

export interface GuestGroupAction extends Action<GuestGroup> {
  getInput(): GuestGroupInput;
}

function randomNum(): string {
  return Math.random().toString(10).substring(2);
}

export class GuestGroupBuilder implements Builder<GuestGroup> {
  private orchestrator: Orchestrator<GuestGroup>;
  readonly placeholderID: ID;
  readonly ent = GuestGroup;
  private input: GuestGroupInput;

  public constructor(
    public readonly viewer: Viewer,
    public readonly operation: WriteOperation,
    action: GuestGroupAction,
    public readonly existingEnt?: GuestGroup | undefined,
  ) {
    this.placeholderID = `$ent.idPlaceholderID$ ${randomNum()}`;
    this.input = action.getInput();

    this.orchestrator = new Orchestrator({
      viewer: viewer,
      operation: this.operation,
      tableName: "guest_groups",
      ent: GuestGroup,
      builder: this,
      action: action,
      schema: schema,
      editedFields: () => {
        return this.getEditedFields.apply(this);
      },
    });
  }

  getInput(): GuestGroupInput {
    return this.input;
  }

  updateInput(input: GuestGroupInput) {
    // override input
    this.input = {
      ...this.input,
      ...input,
    };
  }

  async build(): Promise<Changeset<GuestGroup>> {
    return this.orchestrator.build();
  }

  async valid(): Promise<boolean> {
    return this.orchestrator.valid();
  }

  async validX(): Promise<void> {
    return this.orchestrator.validX();
  }

  async save(): Promise<void> {
    await saveBuilder(this);
  }

  async saveX(): Promise<void> {
    await saveBuilderX(this);
  }

  async editedEnt(): Promise<GuestGroup | null> {
    return await this.orchestrator.editedEnt();
  }

  async editedEntX(): Promise<GuestGroup> {
    return await this.orchestrator.editedEntX();
  }

  private getEditedFields(): Map<string, any> {
    const fields = this.input;

    let result = new Map<string, any>();

    const addField = function (key: string, value: any) {
      if (value !== undefined) {
        result.set(key, value);
      }
    };
    addField("InvitationName", fields.invitationName);
    addField("EventID", fields.eventID);
    return result;
  }

  isBuilder(node: ID | Ent | Builder<Ent>): node is Builder<Ent> {
    return (node as Builder<Ent>).placeholderID !== undefined;
  }
}
