// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { Viewer } from "@snowtop/ent";
import {
  IWithAddressBase,
  WithAddressBaseMixin,
} from "src/ent/generated/mixins/with_address_base";

export interface IWithAddress<TViewer extends Viewer = Viewer>
  extends IWithAddressBase<TViewer> {
  isWithAddress(): boolean;

  // add custom fields
}

type Constructor<T extends IWithAddress = IWithAddress> = new (
  ...args: any[]
) => T;

export function isWithAddress(ent: unknown): ent is IWithAddress {
  const o = ent as IWithAddress;
  return (o.isWithAddress && o.isWithAddress()) ?? false;
}

export function WithAddressMixin<T extends Constructor>(BaseClass: T) {
  return class WithAddressMixin
    extends WithAddressBaseMixin(BaseClass)
    implements IWithAddress
  {
    isWithAddress() {
      return true;
    }

    // add custom fields implementation
  };
}
