// Code generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

package action

import (
	"context"

	"github.com/lolopinto/ent/ent"
	"github.com/lolopinto/ent/ent/actions"
	"github.com/lolopinto/ent/ent/test_schema/models"
	"github.com/lolopinto/ent/ent/test_schema/models/configs"
	"github.com/lolopinto/ent/ent/viewer"
)

type RemoveFamilyMembersAction struct {
	builder *actions.EntMutationBuilder
	user    models.User
}

// RemoveFamilyMembersFromContext is the factory method to get an ...
func RemoveFamilyMembersFromContext(ctx context.Context, user *models.User) *RemoveFamilyMembersAction {
	v, err := viewer.ForContext(ctx)
	if err != nil {
		panic("tried to perform mutation without a viewer")
	}
	return RemoveFamilyMembers(v, user)
}

// RemoveFamilyMembers is the factory method to get an ...
func RemoveFamilyMembers(viewer viewer.ViewerContext, user *models.User) *RemoveFamilyMembersAction {
	builder := &actions.EntMutationBuilder{
		Viewer:         viewer,
		EntConfig:      &configs.UserConfig{},
		Operation:      ent.EditOperation,
		ExistingEntity: user,
	}
	action := &RemoveFamilyMembersAction{}
	builder.FieldMap = action.getFieldMap()
	action.builder = builder
	return action
}

func (action *RemoveFamilyMembersAction) GetViewer() viewer.ViewerContext {
	return action.builder.GetViewer()
}

func (action *RemoveFamilyMembersAction) GetChangeset() (ent.Changeset, error) {
	return action.builder.GetChangeset(action.Entity())
}

func (action *RemoveFamilyMembersAction) Entity() ent.Entity {
	return &action.user
}

// AddUser adds an instance of User to the FamilyMembers edge while editing the User ent
func (action *RemoveFamilyMembersAction) AddUser(user *models.User) *RemoveFamilyMembersAction {
	action.builder.RemoveOutboundEdge(models.UserToFamilyMembersEdge, user.ID, models.UserType)
	return action
}

// AddUser adds an instance of UserId to the FamilyMembers edge while editing the User ent
func (action *RemoveFamilyMembersAction) AddUserID(userID string) *RemoveFamilyMembersAction {
	action.builder.RemoveOutboundEdge(models.UserToFamilyMembersEdge, userID, models.UserType)
	return action
}

// getFieldMap returns the fields that could be edited in this mutation
func (action *RemoveFamilyMembersAction) getFieldMap() ent.MutationFieldMap {
	return ent.MutationFieldMap{}
}

// Validate returns an error if the current state of the action is not valid
func (action *RemoveFamilyMembersAction) Validate() error {
	return action.builder.Validate()
}

// Save is the method called to execute this action and save change
func (action *RemoveFamilyMembersAction) Save() (*models.User, error) {
	err := actions.Save(action)
	return &action.user, err
}

var _ actions.Action = &RemoveFamilyMembersAction{}
