# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column account_state to table accounts
add column related_tag_ids to table tags

Revision ID: 171b49ba3bbb
Revises: 44296aa7aad1
Create Date: 2022-03-30 20:21:41.166647+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '171b49ba3bbb'
down_revision = '44296aa7aad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column(
        'account_state', sa.Text(), nullable=True))
    op.add_column('tags', sa.Column(
        'related_tag_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'related_tag_ids')
    op.drop_column('accounts', 'account_state')
    # ### end Alembic commands ###
