# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column account_prefs_3 to table accounts

Revision ID: 3bd55c3d6b7b
Revises: 17752c0c40ad
Create Date: 2023-02-08 23:02:30.714833+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3bd55c3d6b7b'
down_revision = '17752c0c40ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_prefs_3', sa.Text(
    ), server_default='{"finished_nux":false,"enable_notifs":false,"preferred_language":"en_US"}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_prefs_3')
    # ### end Alembic commands ###
