# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add tags table
add index tags_owner_id_idx to tags

Revision ID: 9cb0712ecc8f
Revises: f5df9362a90e
Create Date: 2021-06-16 05:44:54.572184+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9cb0712ecc8f'
down_revision = 'f5df9362a90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
                    sa.Column('id', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('display_name', sa.Text(), nullable=False),
                    sa.Column('canonical_name', sa.Text(), nullable=False),
                    sa.Column('owner_id', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['owner_id'], ['accounts.id'], name='tags_owner_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='tags_id_pkey'),
                    sa.UniqueConstraint('canonical_name', 'owner_id',
                                        name='uniqueForOwner')
                    )
    op.create_index('tags_owner_id_idx', 'tags', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tags_owner_id_idx', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
