# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column assignee_id to table todos
add column scope_id to table todos
add column scope_type to table todos
add index todos_assignee_id_idx to todos

Revision ID: d203fc688f5e
Revises: 7b1c4bf530c6
Create Date: 2022-10-18 19:27:26.863980+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd203fc688f5e'
down_revision = '7b1c4bf530c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('assignee_id', sa.Text(), nullable=False))
    op.add_column('todos', sa.Column('scope_id', sa.Text(), nullable=False))
    op.add_column('todos', sa.Column('scope_type', sa.Text(), nullable=False))
    op.create_index('todos_assignee_id_idx', 'todos',
                    ['assignee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('todos_assignee_id_idx', table_name='todos')
    op.drop_column('todos', 'scope_type')
    op.drop_column('todos', 'scope_id')
    op.drop_column('todos', 'assignee_id')
    # ### end Alembic commands ###
