# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add todos table
add index todos_completed_idx to todos
add index todos_creator_id_idx to todos

Revision ID: f5df9362a90e
Revises: 702c0c5c0776
Create Date: 2021-06-15 20:51:22.634038+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f5df9362a90e'
down_revision = '702c0c5c0776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
                    sa.Column('id', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('completed', sa.Boolean(), nullable=False),
                    sa.Column('creator_id', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], [
                        'accounts.id'], name='todos_creator_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='todos_id_pkey')
                    )
    op.create_index('todos_completed_idx', 'todos',
                    ['completed'], unique=False)
    op.create_index('todos_creator_id_idx', 'todos',
                    ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('todos_creator_id_idx', table_name='todos')
    op.drop_index('todos_completed_idx', table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
