// Code generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

package action

import (
	"context"

	"github.com/lolopinto/ent/ent"
	"github.com/lolopinto/ent/ent/actions"
	"github.com/lolopinto/ent/ent/viewer"
	"github.com/lolopinto/ent/internal/test_schema/models"
	builder "github.com/lolopinto/ent/internal/test_schema/models/user"
)

type AddFriendAction struct {
	builder *builder.UserMutationBuilder
}

// AddFriendFromContext is the factory method to get an ...
func AddFriendFromContext(ctx context.Context, user *models.User) *AddFriendAction {
	v, err := viewer.ForContext(ctx)
	if err != nil {
		panic("tried to perform mutation without a viewer")
	}
	return AddFriend(v, user)
}

// AddFriend is the factory method to get an ...
func AddFriend(viewer viewer.ViewerContext, user *models.User) *AddFriendAction {
	action := &AddFriendAction{}
	builder := builder.NewMutationBuilder(
		viewer,
		ent.EditOperation,
		action.getFieldMap(),
		actions.ExistingEnt(user),
	)
	action.builder = builder
	return action
}

func (action *AddFriendAction) GetBuilder() ent.MutationBuilder {
	return action.builder
}

func (action *AddFriendAction) GetTypedBuilder() *builder.UserMutationBuilder {
	return action.builder
}

func (action *AddFriendAction) GetViewer() viewer.ViewerContext {
	return action.builder.GetViewer()
}

func (action *AddFriendAction) SetBuilderOnTriggers(triggers []actions.Trigger) error {
	return action.builder.SetTriggers(triggers)
}

func (action *AddFriendAction) SetBuilderOnObservers(observers []actions.Observer) error {
	return action.builder.SetObservers(observers)
}

func (action *AddFriendAction) GetChangeset() (ent.Changeset, error) {
	return actions.GetChangeset(action)
}

func (action *AddFriendAction) Entity() ent.Entity {
	return action.builder.GetUser()
}

func (action *AddFriendAction) ExistingEnt() ent.Entity {
	return action.builder.ExistingEnt()
}

// AddFriends adds an instance of User to the Friends edge while editing the User ent
func (action *AddFriendAction) AddFriends(user *models.User) *AddFriendAction {
	action.builder.AddFriends(user)
	return action
}

// AddFriends adds an instance of UserId to the Friends edge while editing the User ent
func (action *AddFriendAction) AddFriendsID(userID string) *AddFriendAction {
	action.builder.AddFriendsID(userID)
	return action
}

// getFieldMap returns the fields that could be edited in this mutation
func (action *AddFriendAction) getFieldMap() ent.ActionFieldMap {
	return ent.ActionFieldMap{}
}

// Validate returns an error if the current state of the action is not valid
func (action *AddFriendAction) Validate() error {
	return action.builder.Validate()
}

// Save is the method called to execute this action and save change
func (action *AddFriendAction) Save() (*models.User, error) {
	err := actions.Save(action)
	return action.builder.GetUser(), err
}

var _ actions.Action = &AddFriendAction{}
