# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""modify nullable value of column favorite from False to True
modify nullable value of column number_of_calls from False to True
modify nullable value of column pi from False to True

Revision ID: dc8d9b5ec699
Revises: 2b1f9d892318
Create Date: 2019-11-25 23:52:18.234006+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc8d9b5ec699'
down_revision = '2b1f9d892318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('contacts', 'number_of_calls',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contacts', 'pi',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'pi',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('contacts', 'number_of_calls',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contacts', 'favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
