# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add contact_emails table

Revision ID: df1461c4a0dc
Revises: 4044b4003faa
Create Date: 2019-10-29 20:56:34.610977+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df1461c4a0dc'
down_revision = '4044b4003faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_emails',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('email_address', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('contact_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='contact_emails_contact_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contact_emails_id_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_emails')
    # ### end Alembic commands ###
