# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""modify server_default value of column number_of_calls from None to 0

Revision ID: ed135dd00750
Revises: dc8d9b5ec699
Create Date: 2019-11-26 23:40:08.546069+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed135dd00750'
down_revision = 'dc8d9b5ec699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'number_of_calls',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'number_of_calls',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
