# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add db extension postgis
add assoc_edge_config table
add place_reviews table
add place_reviews_edges table
add index place_reviews_edges_time_idx to place_reviews_edges
add places table
add index places_location_gist to places
add user_created_places_edges table
add index user_created_places_edges_time_idx to user_created_places_edges
add user_favorite_places_edges table
add index user_favorite_places_edges_time_idx to user_favorite_places_edges
add user_place_reviews_edges table
add index user_place_reviews_edges_time_idx to user_place_reviews_edges
add users table
add edges PlaceToFansEdge, PlaceToReviewsEdge, UserToCreatedPlacesEdge, UserToFavoritePlacesEdge, UserToPlaceReviewsEdge

Revision ID: a7014dda853b
Revises: 
Create Date: 2026-03-29 22:27:33.688527+00:00

"""
from alembic import op #noqa
import sqlalchemy as sa
import auto_schema


# revision identifiers, used by Alembic.
revision = 'a7014dda853b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_db_extension({'name': 'postgis', 'managed': True, 'version': None, 'install_schema': None, 'runtime_schemas': ['public'], 'drop_cascade': False})
    op.create_table('assoc_edge_config',
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('edge_name', sa.Text(), nullable=False),
    sa.Column('symmetric_edge', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('inverse_edge_type', sa.UUID(), nullable=True),
    sa.Column('edge_table', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['inverse_edge_type'], ['assoc_edge_config.edge_type'], name='assoc_edge_config_inverse_edge_type_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('edge_type', name='assoc_edge_config_edge_type_pkey'),
    sa.UniqueConstraint('edge_name', name='assoc_edge_config_unique_edge_name')
    )
    op.create_table('place_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='place_reviews_id_pkey')
    )
    op.create_table('place_reviews_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='place_reviews_edges_pkey')
    )
    op.create_index('place_reviews_edges_time_idx', 'place_reviews_edges', ['time'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('location', auto_schema.schema_item.CustomSQLAlchemyType('geography(Point,4326)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='places_id_pkey'),
    sa.UniqueConstraint('slug', name='places_unique_slug')
    )
    op.create_index('places_location_gist', 'places', ['location'], unique=False, postgresql_using='gist')
    op.create_table('user_created_places_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='user_created_places_edges_pkey')
    )
    op.create_index('user_created_places_edges_time_idx', 'user_created_places_edges', ['time'], unique=False)
    op.create_table('user_favorite_places_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='user_favorite_places_edges_pkey')
    )
    op.create_index('user_favorite_places_edges_time_idx', 'user_favorite_places_edges', ['time'], unique=False)
    op.create_table('user_place_reviews_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='user_place_reviews_edges_pkey')
    )
    op.create_index('user_place_reviews_edges_time_idx', 'user_place_reviews_edges', ['time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_id_pkey'),
    sa.UniqueConstraint('slug', name='users_unique_slug')
    )
    op.add_edges([
    {'edge_name': 'PlaceToFansEdge', 'edge_type': '2896184f-1cf4-449a-86e9-ee264654bdd3', 'edge_table': 'user_favorite_places_edges', 'symmetric_edge': False, 'inverse_edge_type': 'edbb8c18-80d2-40b6-874a-5350a5e5506a'},
    {'edge_name': 'PlaceToReviewsEdge', 'edge_type': '52594665-1d66-428f-a35d-cbfe162aef9b', 'edge_table': 'place_reviews_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'UserToCreatedPlacesEdge', 'edge_type': '9fcba9cd-1a85-4de4-bdc2-e279fccd0ed8', 'edge_table': 'user_created_places_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'UserToFavoritePlacesEdge', 'edge_type': 'edbb8c18-80d2-40b6-874a-5350a5e5506a', 'edge_table': 'user_favorite_places_edges', 'symmetric_edge': False, 'inverse_edge_type': '2896184f-1cf4-449a-86e9-ee264654bdd3'},
    {'edge_name': 'UserToPlaceReviewsEdge', 'edge_type': 'f5554d92-2939-47d1-86ef-8a6b4f1c8bad', 'edge_table': 'user_place_reviews_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
    {'edge_name': 'PlaceToFansEdge', 'edge_type': '2896184f-1cf4-449a-86e9-ee264654bdd3', 'edge_table': 'user_favorite_places_edges', 'symmetric_edge': False, 'inverse_edge_type': 'edbb8c18-80d2-40b6-874a-5350a5e5506a'},
    {'edge_name': 'PlaceToReviewsEdge', 'edge_type': '52594665-1d66-428f-a35d-cbfe162aef9b', 'edge_table': 'place_reviews_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'UserToCreatedPlacesEdge', 'edge_type': '9fcba9cd-1a85-4de4-bdc2-e279fccd0ed8', 'edge_table': 'user_created_places_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    {'edge_name': 'UserToFavoritePlacesEdge', 'edge_type': 'edbb8c18-80d2-40b6-874a-5350a5e5506a', 'edge_table': 'user_favorite_places_edges', 'symmetric_edge': False, 'inverse_edge_type': '2896184f-1cf4-449a-86e9-ee264654bdd3'},
    {'edge_name': 'UserToPlaceReviewsEdge', 'edge_type': 'f5554d92-2939-47d1-86ef-8a6b4f1c8bad', 'edge_table': 'user_place_reviews_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    op.drop_table('users')
    op.drop_index('user_place_reviews_edges_time_idx', table_name='user_place_reviews_edges')
    op.drop_table('user_place_reviews_edges')
    op.drop_index('user_favorite_places_edges_time_idx', table_name='user_favorite_places_edges')
    op.drop_table('user_favorite_places_edges')
    op.drop_index('user_created_places_edges_time_idx', table_name='user_created_places_edges')
    op.drop_table('user_created_places_edges')
    op.drop_index('places_location_gist', table_name='places', postgresql_using='gist')
    op.drop_table('places')
    op.drop_index('place_reviews_edges_time_idx', table_name='place_reviews_edges')
    op.drop_table('place_reviews_edges')
    op.drop_table('place_reviews')
    op.drop_table('assoc_edge_config')
    op.drop_db_extension({'name': 'postgis', 'managed': True, 'version': None, 'install_schema': None, 'runtime_schemas': ['public'], 'drop_cascade': False})
    # ### end Alembic commands ###
