# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column extra to table contact_emails
add column extra to table contact_phone_numbers

Revision ID: 153a60ecc20e
Revises: 417c89d18d35
Create Date: 2022-10-03 19:25:27.627289+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '153a60ecc20e'
down_revision = '417c89d18d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_emails', sa.Column(
        'extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('contact_phone_numbers', sa.Column(
        'extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_phone_numbers', 'extra')
    op.drop_column('contact_emails', 'extra')
    # ### end Alembic commands ###
