# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add defaults_examples table

Revision ID: 282b186fbda8
Revises: 2ab2809c76a9
Create Date: 2025-11-27 05:40:18.062059+00:00

"""
from alembic import op #noqa
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282b186fbda8'
down_revision = '2ab2809c76a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defaults_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('per_hour', sa.Integer(), server_default='1', nullable=False),
    sa.Column('hourly_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='defaults_examples_id_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defaults_examples')
    # ### end Alembic commands ###
