# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column prefs_list to table users

Revision ID: 3ff8496dfdb9
Revises: e1f9302d78b8
Create Date: 2022-08-14 14:57:42.843469+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ff8496dfdb9'
down_revision = 'e1f9302d78b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'prefs_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prefs_list')
    # ### end Alembic commands ###
