# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""modify server_default value of column date from None to 2020-02-01

Revision ID: 417c89d18d35
Revises: 0d01df7dcc86
Create Date: 2022-09-20 00:19:11.067452+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '417c89d18d35'
down_revision = '0d01df7dcc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holidays', 'date',
                    existing_type=sa.DATE(),
                    server_default='2020-02-01',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holidays', 'date',
                    existing_type=sa.DATE(),
                    server_default=None,
                    existing_nullable=False)
    # ### end Alembic commands ###
