# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""f

Revision ID: 466d862abc01
Revises: bdf63eaa935b
Create Date: 2023-07-20 20:41:09.564707+00:00

"""
from alembic import op
import sqlalchemy as sa
import auto_schema
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '466d862abc01'
down_revision = 'bdf63eaa935b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
