# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column prefs_list to table users

Revision ID: 5ef195f3dacf
Revises: 11ff172242c7
Create Date: 2021-10-14 22:03:50.722846+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ef195f3dacf'
down_revision = '11ff172242c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prefs_list', postgresql.ARRAY(
        postgresql.JSONB(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prefs_list')
    # ### end Alembic commands ###
