# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column article_id to table comments

Revision ID: 63c0cba9c4bb
Revises: 810b35739813
Create Date: 2021-09-21 07:24:20.896104+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63c0cba9c4bb'
down_revision = '810b35739813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column(
        'article_id', postgresql.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'article_id')
    # ### end Alembic commands ###
