# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add edge UserToHostedEventsEdge
modify edge EventToHostsEdge

Revision ID: 64a3bfe652e3
Revises: 2d730d2babea
Create Date: 2020-10-24 20:00:31.319925+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '64a3bfe652e3'
down_revision = '2d730d2babea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_edges([
        {'edge_name': 'UserToHostedEventsEdge', 'edge_type': 'cf6542a4-8bae-427f-8a1f-01194047afb3',
            'edge_table': 'event_hosts_edges', 'symmetric_edge': False, 'inverse_edge_type': 'ebe3e709-845c-4723-ac9c-29f983f2b8ea'},
    ])

    op.modify_edge(
        'ebe3e709-845c-4723-ac9c-29f983f2b8ea',
        {'edge_name': 'EventToHostsEdge', 'edge_type': 'ebe3e709-845c-4723-ac9c-29f983f2b8ea', 'edge_table': 'event_hosts_edges',
            'symmetric_edge': False, 'inverse_edge_type': 'cf6542a4-8bae-427f-8a1f-01194047afb3'},

    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.modify_edge(
        'ebe3e709-845c-4723-ac9c-29f983f2b8ea',
        {'edge_type': UUID('ebe3e709-845c-4723-ac9c-29f983f2b8ea'), 'edge_name': 'EventToHostsEdge', 'symmetric_edge': False,
         'inverse_edge_type': UUID('e5555185-91bf-4322-8130-d0a00eb605b7'), 'edge_table': 'event_hosts_edges'},

    )
    op.remove_edges([
        {'edge_name': 'UserToHostedEventsEdge', 'edge_type': 'cf6542a4-8bae-427f-8a1f-01194047afb3',
            'edge_table': 'event_hosts_edges', 'symmetric_edge': False, 'inverse_edge_type': 'ebe3e709-845c-4723-ac9c-29f983f2b8ea'},
    ])

    # ### end Alembic commands ###
