# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add column owner_id to table contact_emails
add index contact_emails_owner_id_idx to contact_emails
create fk constraint contact_emails_owner_id_fkey on contact_emails
add column owner_id to table contact_phone_numbers
add index contact_phone_numbers_owner_id_idx to contact_phone_numbers
create fk constraint contact_phone_numbers_owner_id_fkey on contact_phone_numbers

Revision ID: 84afa783fc9a
Revises: d644e3adfaa7
Create Date: 2024-03-24 05:40:08.710164+00:00

"""
from alembic import op #noqa
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84afa783fc9a'
down_revision = 'd644e3adfaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_emails', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index('contact_emails_owner_id_idx', 'contact_emails', ['owner_id'], unique=False)
    op.create_foreign_key('contact_emails_owner_id_fkey', 'contact_emails', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('contact_phone_numbers', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index('contact_phone_numbers_owner_id_idx', 'contact_phone_numbers', ['owner_id'], unique=False)
    op.create_foreign_key('contact_phone_numbers_owner_id_fkey', 'contact_phone_numbers', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_phone_numbers_owner_id_fkey', 'contact_phone_numbers', type_='foreignkey')
    op.drop_index('contact_phone_numbers_owner_id_idx', table_name='contact_phone_numbers')
    op.drop_column('contact_phone_numbers', 'owner_id')
    op.drop_constraint('contact_emails_owner_id_fkey', 'contact_emails', type_='foreignkey')
    op.drop_index('contact_emails_owner_id_idx', table_name='contact_emails')
    op.drop_column('contact_emails', 'owner_id')
    # ### end Alembic commands ###
