# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add contact_emails table
add index contact_emails_contact_id_idx to contact_emails
add contact_phone_numbers table
add index contact_phone_numbers_contact_id_idx to contact_phone_numbers

Revision ID: 92217f34d33b
Revises: c5e4df538e0d
Create Date: 2021-12-24 19:49:01.184428+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92217f34d33b'
down_revision = 'c5e4df538e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_emails',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('email_address', sa.Text(), nullable=False),
                    sa.Column('label', sa.Text(), nullable=False),
                    sa.Column('contact_id', postgresql.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['contact_id'], [
                        'contacts.id'], name='contact_emails_contact_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'id', name='contact_emails_id_pkey')
                    )
    op.create_index('contact_emails_contact_id_idx',
                    'contact_emails', ['contact_id'], unique=False)
    op.create_table('contact_phone_numbers',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('phone_number', sa.Text(), nullable=False),
                    sa.Column('label', sa.Text(), nullable=False),
                    sa.Column('contact_id', postgresql.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['contact_id'], [
                        'contacts.id'], name='contact_phone_numbers_contact_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'id', name='contact_phone_numbers_id_pkey')
                    )
    op.create_index('contact_phone_numbers_contact_id_idx',
                    'contact_phone_numbers', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('contact_phone_numbers_contact_id_idx',
                  table_name='contact_phone_numbers')
    op.drop_table('contact_phone_numbers')
    op.drop_index('contact_emails_contact_id_idx', table_name='contact_emails')
    op.drop_table('contact_emails')
    # ### end Alembic commands ###
