# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column preferred_shift to table users

Revision ID: 9c309e28e5b8
Revises: b7436795e6e7
Create Date: 2021-09-23 19:29:33.353716+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c309e28e5b8'
down_revision = 'b7436795e6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_shift',
                  postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_shift')
    # ### end Alembic commands ###
