# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""drop index contact_emails_contact_id_idx from contact_emails
drop constraint contact_emails_contact_id_fkey from contact_emails
drop index contact_phone_numbers_contact_id_idx from contact_phone_numbers
drop constraint contact_phone_numbers_contact_id_fkey from contact_phone_numbers

Revision ID: a5184ce57a3b
Revises: 0c6868c41973
Create Date: 2021-12-24 20:26:53.110792+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a5184ce57a3b'
down_revision = '0c6868c41973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('contact_emails_contact_id_idx', table_name='contact_emails')
    op.drop_constraint('contact_emails_contact_id_fkey',
                       'contact_emails', type_='foreignkey')
    op.drop_index('contact_phone_numbers_contact_id_idx',
                  table_name='contact_phone_numbers')
    op.drop_constraint('contact_phone_numbers_contact_id_fkey',
                       'contact_phone_numbers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('contact_phone_numbers_contact_id_fkey', 'contact_phone_numbers', 'contacts', [
                          'contact_id'], ['id'], ondelete='CASCADE')
    op.create_index('contact_phone_numbers_contact_id_idx',
                    'contact_phone_numbers', ['contact_id'], unique=False)
    op.create_foreign_key('contact_emails_contact_id_fkey', 'contact_emails', 'contacts', [
                          'contact_id'], ['id'], ondelete='CASCADE')
    op.create_index('contact_emails_contact_id_idx',
                    'contact_emails', ['contact_id'], unique=False)
    # ### end Alembic commands ###
