# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add column on_demand_non_nullable_list to table users

Revision ID: b0e503a0e790
Revises: 8332d4d0d49f
Create Date: 2025-12-24 07:39:30.460679+00:00

"""
from alembic import op #noqa
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0e503a0e790'
down_revision = '8332d4d0d49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('on_demand_non_nullable_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'on_demand_non_nullable_list')
    # ### end Alembic commands ###
