# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add global_login_auth_edges table
add index global_login_auth_edges_time_idx to global_login_auth_edges
add edge GlobalToLoginAuthEdge

Revision ID: cca3dbdf4c48
Revises: d1e063da4a0c
Create Date: 2022-07-28 06:07:18.688634+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cca3dbdf4c48'
down_revision = 'd1e063da4a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_login_auth_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='global_login_auth_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('global_login_auth_edges_time_idx',
                    'global_login_auth_edges', ['time'], unique=False)
    op.add_edges([
        {'edge_name': 'GlobalToLoginAuthEdge', 'edge_type': '13eb6687-d226-4272-ba65-d5e33e00954c',
            'edge_table': 'global_login_auth_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'GlobalToLoginAuthEdge', 'edge_type': '13eb6687-d226-4272-ba65-d5e33e00954c',
            'edge_table': 'global_login_auth_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    op.drop_index('global_login_auth_edges_time_idx',
                  table_name='global_login_auth_edges')
    op.drop_table('global_login_auth_edges')
    # ### end Alembic commands ###
