# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add contact_email_emails_for_contacts_edges table
add index contact_email_emails_for_contacts_edges_time_idx to contact_email_emails_for_contacts_edges
add edge ContactEmailToEmailsForContactsEdge

Revision ID: dcbf0fe20ae0
Revises: b0e503a0e790
Create Date: 2025-12-26 06:30:46.888489+00:00

"""
from alembic import op #noqa
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbf0fe20ae0'
down_revision = 'b0e503a0e790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_email_emails_for_contacts_edges',
    sa.Column('id1', sa.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.UUID(), nullable=False),
    sa.Column('id2', sa.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='contact_email_emails_for_contacts_edges_id1_edge_type_id2_pkey')
    )
    op.create_index('contact_email_emails_for_contacts_edges_time_idx', 'contact_email_emails_for_contacts_edges', ['time'], unique=False)
    op.add_edges([
    {'edge_name': 'ContactEmailToEmailsForContactsEdge', 'edge_type': 'daee7f0d-264f-44da-b2ff-5481e4143b22', 'edge_table': 'contact_email_emails_for_contacts_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
    {'edge_name': 'ContactEmailToEmailsForContactsEdge', 'edge_type': 'daee7f0d-264f-44da-b2ff-5481e4143b22', 'edge_table': 'contact_email_emails_for_contacts_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    op.drop_index('contact_email_emails_for_contacts_edges_time_idx', table_name='contact_email_emails_for_contacts_edges')
    op.drop_table('contact_email_emails_for_contacts_edges')
    # ### end Alembic commands ###
