# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""drop column prefs_list from table users

Revision ID: e1f9302d78b8
Revises: cca3dbdf4c48, f9fc71f5ba8f
Create Date: 2022-08-14 14:57:04.802644+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1f9302d78b8'
down_revision = ('cca3dbdf4c48', 'f9fc71f5ba8f')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prefs_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prefs_list', postgresql.ARRAY(
        postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
