# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column local_utc_offset to table events

Revision ID: e27f63738b66
Revises: bdf63eaa935b
Create Date: 2023-06-28 22:39:06.294194+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e27f63738b66'
down_revision = 'bdf63eaa935b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column(
        'local_utc_offset', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'local_utc_offset')
    # ### end Alembic commands ###
