# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column name_idx to table users
add index user_name_idx to users

Revision ID: ec6dc2a39e74
Revises: 42b21a3bccc5
Create Date: 2022-04-27 17:38:18.829682+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec6dc2a39e74'
down_revision = '42b21a3bccc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_idx', postgresql.TSVECTOR(), sa.Computed(
        "to_tsvector('simple', coalesce(first_name, '') || ' ' || coalesce(last_name, ''))", ), nullable=True))
    op.create_index('user_name_idx', 'users', [
                    'name_idx'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_name_idx', table_name='users', postgresql_using='gin')
    op.drop_column('users', 'name_idx')
    # ### end Alembic commands ###
