# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add column cover_photo2 to table events
drop column cover_photo_2 from table events
add column new_col2 to table users
drop column new_col_2 from table users

Revision ID: efb5231162ba
Revises: ab740b21dca2
Create Date: 2024-02-19 04:28:30.239537+00:00

"""
from alembic import op #noqa
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb5231162ba'
down_revision = 'ab740b21dca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('cover_photo2', sa.Text(), nullable=True))
    op.drop_column('events', 'cover_photo_2')
    op.add_column('users', sa.Column('new_col2', sa.Text(), nullable=True))
    op.drop_column('users', 'new_col_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_col_2', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'new_col2')
    op.add_column('events', sa.Column('cover_photo_2', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('events', 'cover_photo2')
    # ### end Alembic commands ###
