# Code generated by github.com/lolopinto/ent/ent, DO NOT edit. 

"""add user_self_contact_edges table
add edge UserToSelfContactEdge

Revision ID: fe26542bbd4c
Revises: 78fa1d22bf42
Create Date: 2020-03-18 20:10:18.520722+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe26542bbd4c'
down_revision = '78fa1d22bf42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_self_contact_edges',
    sa.Column('id1', postgresql.UUID(), nullable=False),
    sa.Column('id1_type', sa.Text(), nullable=False),
    sa.Column('edge_type', postgresql.UUID(), nullable=False),
    sa.Column('id2', postgresql.UUID(), nullable=False),
    sa.Column('id2_type', sa.Text(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2', name='user_self_contact_edges_id1_edge_type_id2_pkey'),
    sa.UniqueConstraint('id1', 'edge_type', name='user_self_contact_edges_unique_id1_edge_type')
    )
    op.add_edges(
      [
        {'edge_name': 'UserToSelfContactEdge', 'edge_type': 'd504201d-cf3f-4eef-b6a0-0b46a7ae186b', 'edge_table': 'user_self_contact_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
      ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges(
      [
        {'edge_name': 'UserToSelfContactEdge', 'edge_type': 'd504201d-cf3f-4eef-b6a0-0b46a7ae186b', 'edge_table': 'user_self_contact_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
      ]
    )
    op.drop_table('user_self_contact_edges')
    # ### end Alembic commands ###
