name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    # Service containers to run with `build`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '>3.6' 
      
    - name: install auto_schema
      run: python3 -m pip install auto_schema==0.0.3

    - name: Build
      run: go build -v ./...
      
    - name: setup db
      run: cd test_setup && go run .
      env:
          # format of this string is different for python
          # if the logic here changes and we need to access golang, we'd need to rewrite this
          DB_CONNECTION_STRING: postgresql+pg8000://postgres:postgres@localhost:5432/postgres

    - name: Test
      run: PATH_TO_DB_FILE=testdata/config/database.yml DB_CONNECTION_STRING=postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable go test ./... -v -short 




