# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./python/auto_schema

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
          
      sqlite:
        image: nouchka/sqlite3
          
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip 
        pip install pipenv==2018.11.26

    - name: Install dependencies
      run: | 
        pipenv install -deploy -dev

    - name: run test suite
      run: |
        pipenv shell
        python -m pytest -svvv
      env: 
        DB_CONNECTION_STRING: 'postgres://postgres:postgres@localhost:5432/postgres'
