type Query {
  address(id: ID!): Address
  authCode(id: ID!): AuthCode
  contact(id: ID!): Contact
  event(id: ID!): Event
  user(id: ID!): User
  viewer: Viewer!
}

type Address {
  id: ID!
  streetName: String!
  city: String!
  zip: String!
}

type AuthCode {
  user: User
  id: ID!
  code: String!
  emailAddress: String!
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  emailAddress: String!
  phoneNumber: String
  accountStatus: String
  bio: String
  createdEvents(first: Int, after: String, last: Int, before: String): UserToCreatedEventsConnection!
  friends(first: Int, after: String, last: Int, before: String): UserToFriendsConnection!
  selfContact: Contact
  userToHostedEvents(first: Int, after: String, last: Int, before: String): UserToHostedEventsConnection!
  invitedEvents(first: Int, after: String, last: Int, before: String): UserToInvitedEventsConnection!
  eventsAttending(first: Int, after: String, last: Int, before: String): UserToEventsAttendingConnection!
  declinedEvents(first: Int, after: String, last: Int, before: String): UserToDeclinedEventsConnection!
  maybeEvents(first: Int, after: String, last: Int, before: String): UserToMaybeEventsConnection!
  authCodes: [AuthCode!]!
  contacts: [Contact!]!
  fullName: String!
  bar: String
  contactSameDomain: Contact
  contactsSameDomain: [Contact!]!
  contactsSameDomainNullable: [Contact!]
  contactsSameDomainNullableContents: [Contact]!
  contactsSameDomainNullableContentsAndList: [Contact]
}

type UserToCreatedEventsConnection {
  edges: [UserToCreatedEventsEdge!]!
  nodes: [User!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type UserToCreatedEventsEdge {
  node: User!
  cursor: String!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

type UserToFriendsConnection {
  edges: [UserToFriendsEdge!]!
  nodes: [User!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type UserToFriendsEdge {
  node: User!
  cursor: String!
}

type Contact {
  user: User
  id: ID!
  emailAddress: String!
  firstName: String!
  lastName: String!
  fullName: String!
}

type UserToHostedEventsConnection {
  edges: [UserToHostedEventsEdge!]!
  nodes: [User!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type UserToHostedEventsEdge {
  node: User!
  cursor: String!
}

type UserToInvitedEventsConnection {
  edges: [UserToInvitedEventsEdge!]!
  nodes: [User!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type UserToInvitedEventsEdge {
  node: User!
  cursor: String!
}

type UserToEventsAttendingConnection {
  edges: [UserToEventsAttendingEdge!]!
  nodes: [User!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type UserToEventsAttendingEdge {
  node: User!
  cursor: String!
}

type UserToDeclinedEventsConnection {
  edges: [UserToDeclinedEventsEdge!]!
  nodes: [User!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type UserToDeclinedEventsEdge {
  node: User!
  cursor: String!
}

type UserToMaybeEventsConnection {
  edges: [UserToMaybeEventsEdge!]!
  nodes: [User!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type UserToMaybeEventsEdge {
  node: User!
  cursor: String!
}

type Event {
  creator: User
  id: ID!
  name: String!
  startTime: Time!
  endTime: Time
  eventLocation: String!
  hosts(first: Int, after: String, last: Int, before: String): EventToHostsConnection!
  invited(first: Int, after: String, last: Int, before: String): EventToInvitedConnection!
  attending(first: Int, after: String, last: Int, before: String): EventToAttendingConnection!
  declined(first: Int, after: String, last: Int, before: String): EventToDeclinedConnection!
  maybe(first: Int, after: String, last: Int, before: String): EventToMaybeConnection!
}

"""Time scalar type"""
scalar Time

type EventToHostsConnection {
  edges: [EventToHostsEdge!]!
  nodes: [Event!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type EventToHostsEdge {
  node: Event!
  cursor: String!
}

type EventToInvitedConnection {
  edges: [EventToInvitedEdge!]!
  nodes: [Event!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type EventToInvitedEdge {
  node: Event!
  cursor: String!
}

type EventToAttendingConnection {
  edges: [EventToAttendingEdge!]!
  nodes: [Event!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type EventToAttendingEdge {
  node: Event!
  cursor: String!
}

type EventToDeclinedConnection {
  edges: [EventToDeclinedEdge!]!
  nodes: [Event!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type EventToDeclinedEdge {
  node: Event!
  cursor: String!
}

type EventToMaybeConnection {
  edges: [EventToMaybeEdge!]!
  nodes: [Event!]!
  pageInfo: PageInfo!
  rawCount: Int!
}

type EventToMaybeEdge {
  node: Event!
  cursor: String!
}

type Viewer {
  viewerID: ID
  user: User
}

type Mutation {
  authCodeDelete(input: AuthCodeDeleteInput!): AuthCodeDeleteResponse!
  confirmEditEmailAddressEdit(input: ConfirmEditEmailAddressEditInput!): ConfirmEditEmailAddressEditResponse!
  contactCreate(input: ContactCreateInput!): ContactCreateResponse!
  contactDelete(input: ContactDeleteInput!): ContactDeleteResponse!
  contactEdit(input: ContactEditInput!): ContactEditResponse!
  emailAddressEdit(input: EmailAddressEditInput!): EmailAddressEditResponse!
  eventAddHost(input: EventAddHostInput!): EventAddHostResponse!
  eventCreate(input: EventCreateInput!): EventCreateResponse!
  eventDelete(input: EventDeleteInput!): EventDeleteResponse!
  eventEdit(input: EventEditInput!): EventEditResponse!
  userAuth(input: UserAuthInput!): UserAuthResponse!
  userAuthJWT(input: UserAuthJWTInput!): UserAuthJWTResponse!
  userCreate(input: UserCreateInput!): UserCreateResponse!
  userDelete(input: UserDeleteInput!): UserDeleteResponse!
  userEdit(input: UserEditInput!): UserEditResponse!
}

type AuthCodeDeleteResponse {
  deletedAuthCodeID: ID
}

input AuthCodeDeleteInput {
  authCodeID: ID!
}

type ConfirmEditEmailAddressEditResponse {
  user: User!
}

input ConfirmEditEmailAddressEditInput {
  userID: ID!
  emailAddress: String
  code: String!
}

type ContactCreateResponse {
  contact: Contact!
}

input ContactCreateInput {
  emailAddress: String!
  firstName: String!
  lastName: String!
  userID: String!
}

type ContactDeleteResponse {
  deletedContactID: ID
}

input ContactDeleteInput {
  contactID: ID!
}

type ContactEditResponse {
  contact: Contact!
}

input ContactEditInput {
  contactID: ID!
  emailAddress: String
  firstName: String
  lastName: String
  userID: String
}

type EmailAddressEditResponse {
  user: User!
}

input EmailAddressEditInput {
  userID: ID!
  newEmail: String!
}

type EventAddHostResponse {
  event: Event!
}

input EventAddHostInput {
  eventID: ID!
  hostID: ID!
}

type EventCreateResponse {
  event: Event!
}

input EventCreateInput {
  name: String!
  creatorID: String!
  startTime: Time!
  endTime: Time
  eventLocation: String!
}

type EventDeleteResponse {
  deletedEventID: ID
}

input EventDeleteInput {
  eventID: ID!
}

type EventEditResponse {
  event: Event!
}

input EventEditInput {
  eventID: ID!
  name: String
  creatorID: String
  startTime: Time
  endTime: Time
  eventLocation: String
}

type UserAuthResponse {
  token: String!
  viewerID: ID!
}

input UserAuthInput {
  emailAddress: String!
  password: String!
}

type UserAuthJWTResponse {
  token: String!
  viewerID: ID!
}

input UserAuthJWTInput {
  emailAddress: String!
  password: String!
}

type UserCreateResponse {
  user: User!
}

input UserCreateInput {
  firstName: String!
  lastName: String!
  emailAddress: String!
  phoneNumber: String!
  password: String!
}

type UserDeleteResponse {
  deletedUserID: ID
}

input UserDeleteInput {
  userID: ID!
}

type UserEditResponse {
  user: User!
}

input UserEditInput {
  userID: ID!
  firstName: String
  lastName: String
}
